### ISSUE TITLE
ReleaseBB issue

### ISSUE THREAD

**Issue by aconer81** [bugatsinho/bugatsinho.github.io#1]
Hey thanks for all your hard work much appreciated this is one of my favorite addons. after the last 2 updates to ver 1.2.1 the addon isn't working for me anymore every time I click on a movie I get an error saying sorry there was a problem please try again then the movie comes out blank with no links or just the trailer. I dunno if the issue is on my end or what but itried clearing all caches anything I could think of with no success I finally downloaded ver 1.1.1 from GitHub and downgraded back to it on kodi and now I still get the same error msg except now the addon works and every movie is producing plenty of links again. Thanks 4 any help with the issue and again appreciate all your hard work have a good night

**Comment by bugatsinho** [comment]
plz provide a kodi log file after you get the error.
you can use kodi logfile uploader add-on from official kodi repository and use the upload method and just paste here the provided link.
thank you

**Comment by bugatsinho** [comment]
Seems like the website is under attack mode using cloudflare!it will be fixed in next update.
