### ISSUE TITLE
Sporthd's 0.1.18 new menu (live events) is broken

### ISSUE THREAD

**Issue by pitsi** [bugatsinho/bugatsinho.github.io#101]
I got the upgrade to 0.1.18 earlier and I noticed that the old "new view" menu entry, which was introduced in 0.1.12 (early February, because of a change in the site itself), has been replaced with "live events". so I tried it.

And the addon now loops around the main menu and the dates, e.g I select live events > the dates appear > I select a date > the main menu appears again > I select live events again > the dates appear again > I select a date again > the main menu appears again and the loop goes on forever.
Unfortunately, the log gives no output at all when anything in the menu is pressed, so I have nothing to post and help you more.

The above was tested on kodi 18.9 and 19.4, producing the same result.

**Comment by kolekan** [comment]
@bugatsinho 
https://github.com/bugatsinho/bugatsinho.github.io/pull/102

**Comment by pitsi** [comment]
The issue was fixed, so I am closing this report. Thank you for the quick response.
For a future update, please consider fixing the following minor issues 
- selecting the dates reproduces the forementioned loop behavior, so please make them unselectable
- cancelling (= pressing back) when the url selection window is open goes to a blank menu instead of the main one with the games

**Comment by bugatsinho** [comment]
thank you @pitsi  i will do it ASAP
