### ISSUE TITLE
RELEASE HUB - SCENE RELEASE NOT WORKING

### ISSUE THREAD

**Issue by Scritti69** [bugatsinho/bugatsinho.github.io#103]
Firstly, apologies if I've done any of this wrong - I'm guessing my way through this as I literally just created a Github account to post this so I don't really know what I'm doing but it looks like this is the way I flag up an issue.

Scene Release on Release Hub stopped working for me about 10 days or so ago. I know it sometimes happens but is usually working again after a week or so so wanted to flag this in case there is anything you can do. RlsHub works fine and I can enter Scene Release but it just gives an error when you click on TV or Movies etc. 

Hope you can help as I love this addon, especially the Scene Release section is it's the most comprehensive I've found. No worries if not and massive thanks for everything you do. Thank you.

**Comment by bugatsinho** [comment]
I will push an update ASAP for scene release

**Comment by Scritti69** [comment]
Okay, thanks very much, appreciate it!
