### ISSUE TITLE
Choose Stream menu loop 

### ISSUE THREAD

**Issue by albilu** [bugatsinho/bugatsinho.github.io#108]
Hello, When picking a stream the player start well but the Choose Stream menu comes back and when clicking on cancel it stops the player.

Seems like a loop on Choose Stream menu.

I am using Kodi 19.3 on Android TV
SportHD version 0.1.26a

Any advice please?
Thansks

**Comment by bugatsinho** [comment]
Just test it myself but no issue comes up in my nvidia shield! Please reinstall add-on and provide kodi log file
after enabling debuging.
thank you

**Comment by albilu** [comment]
Thanks for the help. After deleting Kodi userdata it went back to working.
