### ISSUE TITLE
Index Error SportHD

### ISSUE THREAD

**Issue by angpaul** [bugatsinho/bugatsinho.github.io#109]
When opening streams I get the following error on Kodi 19.3 Android. It was working fine on Saturday 27 of August. Problem started yesterday 

![Screenshot_20220829-121907_Kodi](https://user-images.githubusercontent.com/112386531/187170530-332710cc-1a92-41ed-9201-cf0bcd773a9a.jpg)
![Screenshot_20220829-121947_Kodi](https://user-images.githubusercontent.com/112386531/187170575-e16ae7ac-21a2-49fa-afa8-04c0080c0042.jpg)

**Comment by bugatsinho** [comment]
https://github.com/bugatsinho/bugatsinho.github.io/commit/a6e5e2c8354a4a77828765234178cdcc87070ff8
