### ISSUE TITLE
Sport HD on Nexus?

### ISSUE THREAD

**Issue by Musiktoto** [bugatsinho/bugatsinho.github.io#116]
Hello!
Thank you for this great Addon.
Is there any chance of making Sport HD fit for Kodi Nexus?
I would be very happy about an update.
Thanks

**Comment by bugatsinho** [comment]
Hi mate, can you elaborate me on your request?
As I've checked add-on is working
![image](https://user-images.githubusercontent.com/18536253/210207621-9548d79b-e04d-4257-b1fd-16a4e8fcde4e.png)

**Comment by xalagaco** [comment]
I upgraded to Nexus and Sport HD does work, however the bugatsinho repo only shows SMR Link Tester under video addons.

**Comment by bugatsinho** [comment]
> I upgraded to Nexus and Sport HD does work, however the bugatsinho repo only shows SMR Link Tester under video addons.

get the latest repository!
