### ISSUE TITLE
RLSBB "please try other link!"

### ISSUE THREAD

**Issue by hendoben** [bugatsinho/bugatsinho.github.io#122]
getting this error for every link lately.. tried all the usual fixes but seems the add-on might be broken?

**Comment by bugatsinho** [comment]
maybe you have to reauthorize your debrid account mate. thats my guess. next time provide the kodi.log

**Comment by hendoben** [comment]
I've tried that multiple times. I'll provide a log later.

**Comment by bugatsinho** [comment]
as i checked movie's domain are under cloudflare so not a workaround to get links sorry

**Comment by deadhead51** [comment]
Hi I've been having the same problem for the last couple of days. My debrid us authorised but I'm not getting any links at all, it just says try a different link. I get all the programs in tv shows but no links to watch.

**Comment by bugatsinho** [comment]
before commented read above.
