### ISSUE TITLE
Information please

### ISSUE THREAD

**Issue by Pawman63** [bugatsinho/bugatsinho.github.io#124]
I am not sure if you know the answer to this, when I use rlsbb any of the links .mov .cc .to even with a vpn the titles appear but on selecting get try another link, is the main site screwed or is the issue resolve based etc?

**Comment by jackinut** [comment]
how do i pay you none of you links works also why is it so hard to contact you bughatsinho

**Comment by Arthur1967** [comment]
Join the Telegram group mine is working fine

**Comment by bugatsinho** [comment]
It's not hard to find me mate! We are in my group chat in telegram. join us

**Comment by jackinut** [comment]
please will you send info on how to pay ive tried the other way and paypal won't accept my bb works for 3 programs and stops so i thought you might want paying send me a proper email account thanks jackie

**Comment by jackinut** [comment]
tried but i have to link my phone as well and its to much for me before you could use Direct from  pc not now there's no way around it  all i want is to pay you some money could you send email address as your link does not work i need the bb i get to watch 3 shows then its goes off ive tried changing to diff country but it wont work


Jackie Nuttall
________________________________

**Comment by bugatsinho** [comment]
Maybe you misunderstood. you can join the group without show your phone number but anyway. Keep your money and thank you but i can't help you. You can search and see videos about SYNCLER and watch your tvshows. thank you
