### ISSUE TITLE
Sporthd  No live event opens

### ISSUE THREAD

**Issue by Rick654** [bugatsinho/bugatsinho.github.io#132]
HI . I've been opening the addon for a few days, but when I try to open the live events it gives me an error and nothing happens. I use kodi 19 windows 10
[kodi.log](https://github.com/bugatsinho/bugatsinho.github.io/files/13301972/kodi.log)

**Comment by Rick654** [comment]
Good morning, nothing to do friend?
I'm sorry that I can't use it

**Comment by bugatsinho** [comment]
Probay your isp is blocking the access to the website.

**Comment by lorieje** [comment]
Indeed i have the same issue using kodi 20.2 with linux mint, clicking on live events generate an sportHD error.
some lines from kodi.log
File "/home/lorieje/.kodi/addons/plugin.video.sporthdme/default.py", line 767, in <module>
                                                       get_events(url)
                                                     File "/home/lorieje/.kodi/addons/plugin.video.sporthdme/default.py", line 165, in get_events
                                                       data = client.request(url)
                                                     File "/home/lorieje/.kodi/addons/plugin.video.sporthdme/resources/modules/client.py", line 128, in request
rror <general>: GetDirectory - Error getting plugin://plugin.video.sporthdme/?description&iconimage=%2fhome%2florieje%2f.kodi%2faddons%2fplugin.video.sporthdme%2ficon.png&mode=5&name=%5bB%5d%5bCOLOR%20white%5dLIVE%20EVENTS%5b%2fCOLOR%5d%5b%2fB%5d&url=https%3a%2f%2fmy.livesoccer.sx%2f
Thanks of having a look, regards
