### ISSUE TITLE
Problems with SportsHD and Kodi Omega

### ISSUE THREAD

**Issue by Grabber66** [bugatsinho/bugatsinho.github.io#137]
Hi,
i have some problems with sportshd an the omega builds.
Here i can start every stream, but at the same time the stream select-window appears again. 
And if i close this, the stream stops.
With Kodi Nexus there is no problem at all.

**Comment by mmsot** [comment]
I have the same problem. Is there any workaround?

**Comment by bugatsinho** [comment]
The workout is to install latest omega RC version cause this issue is KODI issue

**Comment by Grabber66** [comment]
Thanks this works.

**Comment by mmsot** [comment]
Yes thank you very much. It worked
