### ISSUE TITLE
[CartoonsGR] GanatoTV links return movies, not cartoons

### ISSUE THREAD

**Issue by loukvlav** [bugatsinho/bugatsinho.github.io#139]
Something must have changed in gamato tv site. Could you please update the plugin to show cartoons again?

**Comment by loukvlav** [comment]
Hi again, I saw links are updated but it still gives an error when it loads. Could you please have a look?

**Comment by bugatsinho** [comment]
error when it loads what exactly? can you be more specific plz?

**Comment by pitsi** [comment]
Sorry for the late reply, but I was too busy yesterday to get logs etc. 

The domain of gamatostatus went offline and broke the `GAMATO` variable on line 82 and, in turn, the entire default.py. I tried patching it, by adding the new domain as the `GAMATO` variable on line 82. This made the addon launch again, but nothing played under gamato, so I wanted to post a log from that.

Now everything is fixed. Thank you :)
