### ISSUE TITLE
 Bugatsinho 2.7 

### ISSUE THREAD

**Issue by MaKud** [bugatsinho/bugatsinho.github.io#140]
SportHD V 0.1.40 always SportHD error.
Bugatsinho 2.7 from https://bugatsinho.github.io/repo/ reinstalled in Kodi 20.3, but there is no SportHD included.
What am I doing wrong?
Thanks for your help

**Comment by bugatsinho** [comment]
Try to Reinstall repository
No idea why you are not seeing the addon

**Comment by MaKud** [comment]
Thanks, as I said repository reinstalled as before. But only CartoonsGR, ReleaseHUB, ReleaseBB, Skyline WebCams and SMR Link Tester appear.
I am at a loss !

**Comment by MaKud** [comment]
Tested again. This time on Android, previously Windows. SportHD appears there. But when opening the links still SportHD error.

**Comment by bugatsinho** [comment]
> Tested again. This time on Android, previously Windows. SportHD appears there. But when opening the links still SportHD error.

can you provide the streams that not work? 

s2watch streams work for now

**Comment by bugatsinho** [comment]
also coolrea and smycdn resolvers fixed
