### ISSUE TITLE
ReleaseBB

### ISSUE THREAD

**Issue by Arthur1967** [bugatsinho/bugatsinho.github.io#142]
Everything is taking a long time to show up just started yesterday morning

**Comment by Arthur1967** [comment]
Still going to slow, but it could be because I'm using kodi 20.3 thanks

**Comment by Arthur1967** [comment]
That was a typo. It's going kind of slow, but it could be the version of. Kodi I'm using.

**Comment by bugatsinho** [comment]
or it could be the website. In any case i will check again when i will be back

**Comment by Arthur1967** [comment]
Thanks
