### ISSUE TITLE
GreekSubs on 19.5

### ISSUE THREAD

**Issue by BillyNtV** [bugatsinho/bugatsinho.github.io#143]
I have installed the greekubs in my MacBook in the 19.5.0 kodi version. I have installed the greeksubs in a Xiaomi tv-box in 20.3.2 version.
In the same episode of a series from the same add-on, in my MacBook greeksubs gives me only one subtitle and in the tv-box over 10 subtitles.
please somebody tell me what I have to do.

Thank You

**Comment by bugatsinho** [comment]
Nothing to say for sure cause I don't know your set ups.
I can imagine that in your Mac you saw only subs from subztv and your xiaomi you get from s4f and subztv. 
Also don't have solution to this issue cause as far i've checked s4f website doesnt return always subs. Also my guess is that in your mac you didn't change your ISP DNS to Google or cloudflare one.
