### ISSUE TITLE
My google tv has problem or it doesnt work?

### ISSUE THREAD

**Issue by DantesRevengeReloaded** [bugatsinho/bugatsinho.github.io#147]
Hi, it cant open the list, i got several log errors my version is the last one, should i reinstall add on if these happen? ![IMG_20240402_224203.jpg](https://github.com/bugatsinho/bugatsinho.github.io/assets/119972346/f21bce13-9c6e-436c-9a56-eea047865f43)

**Comment by pitsi** [comment]
How old is your installation? Because the repo's compatibily with kodi 20+ (which is what the errors tell you) has been resolved with v2.6, which was released like 15+ months ago.

**Comment by DantesRevengeReloaded** [comment]
i reinstalled kodi and repo from scratch, still i get the errors which occurred the last few days and it happens both in my phone and my google tv, with the difference that in my phone it opens the folder and it is blank, i will check if there is blocking from isp but its strange it happens only to me. I even installed in pc and it doesnt work in fresh installation

**Comment by bugatsinho** [comment]
Those errors in the pic aren't from my addon though. so can't help you out

**Comment by bugatsinho** [comment]
try the new version 0.1.50 and you will be fine.
https://github.com/bugatsinho/bugatsinho.github.io/commit/1dd2898b46511f11897d3036112828cca32c4c76
