### ISSUE TITLE
Sporthd index error

### ISSUE THREAD

**Issue by beluchon** [bugatsinho/bugatsinho.github.io#150]

**Comment by beluchon** [comment]
Hello since yesterday evening I have an error and I tried to reinstall sporthd, vpn, change dns but nothing changes.![image](https://github.com/bugatsinho/bugatsinho.github.io/assets/118637341/0aef4f66-131d-4da9-859c-7e98bc251847)

**Comment by MaKud** [comment]
Hello,
I have the same error as beluchon!
Thank you

**Comment by bugatsinho** [comment]
Fixed with last update 0.1.53

**Comment by hoke-81** [comment]
Seems to be there again, I coul watch last week, today "list index out of range" on two devices
