### ISSUE TITLE
GreekSubs Error

### ISSUE THREAD

**Issue by etsicode** [bugatsinho/bugatsinho.github.io#153]
Subs4Series does not return anything.

**Comment by bugatsinho** [comment]
Try to open the website in a browser at the same network and try again. I will check during the week if there is any issue.

**Comment by etsicode** [comment]
From the website I can search successfully.

**Comment by bugatsinho** [comment]
No I'm saying to open first in a browser and then try on kodi!

**Comment by etsicode** [comment]
This is exactly what I did. The problem persists. From the site subs4free I have no problem with subtitles. The problem is with subs4series when I search for a tv subtitle.

**Comment by kolekan** [comment]
Propably you are using an addon that is not passing tv show metadata to kodi player. No issue for me.

**Comment by etsicode** [comment]
Tested with 2 video addons: **Fen light** and **umbrella** with increased timeout to 30. Same behaviour. 
Other subtitle addons like **opensubtitles** and the same addon on other websites like **SubzTV** give expected results.

**Comment by kolekan** [comment]
![IMG_20240624_183145](https://github.com/bugatsinho/bugatsinho.github.io/assets/35860760/5dad9b4e-634f-43ec-85b1-e147b15a5eaa)
As you can see there is no issue. Change your network dns servers to google or cloudflare.

**Comment by kolekan** [comment]
> My dns servers are set to google.

Is this set both for ipv4 and ipv6?

**Comment by etsicode** [comment]
For ip4 and ip6 the dns severs are set to google.
