### ISSUE TITLE
SportHD Error

### ISSUE THREAD

**Issue by alien8tor** [bugatsinho/bugatsinho.github.io#156]
Hi, Just wondering if anyone else is experiencing issue with SportHD, was working fine last night, today I've noticed when I click on "live events" after while it says "No Match Scheduled".

Can anyone confirm if there is any problems loading SportHD?

**Comment by kolekan** [comment]
if you can't visit the website from the internet browser don't expect sporthd addon to do it.
Site is down at the moment.

**Comment by PAPADH** [comment]
TΟ SPORTHD ΟΤΑΝ ΜΕΤΑΔΊΔΕΙ ΕΛΛΗΝΙΚΟΥΣ ΑΓΩΝΕΣ ΚΟΛΛΆΕΙ ΣΥΝΕΧΕΙ ΜΕ ΤΗΝ ΤΕΛΕΥΤΑΊΑ ΕΚΔΩΣΗ ΕΝΩ ΔΕΝ ΣΥΜΒΑΊΝΕΙ ΜΕ ΤΟ ΠΡΟΣΘΕΤΟ APEX SPORTS

**Comment by PAPADH** [comment]
> TΟ SPORTHD ΟΤΑΝ ΜΕΤΑΔΊΔΕΙ ΕΛΛΗΝΙΚΟΥΣ ΑΓΩΝΕΣ ΚΟΛΛΆΕΙ ΣΥΝΕΧΕΙA ΜΕ ΤΗΝ ΤΕΛΕΥΤΑΊΑ ΕΚΔΩΣΗ ΕΝΩ ΔΕΝ ΣΥΜΒΑΊΝΕΙ ΜΕ ΤΟ ΠΡΟΣΘΕΤΟ APEX SPORTS
