### ISSUE TITLE
Sports HD watching soccer it just got disconnected when the match is not even finishing

### ISSUE THREAD

**Issue by mrusli70** [bugatsinho/bugatsinho.github.io#157]
While watching the soccer the live match connection some how get disconnected. You guys need to improve and fix the problems with the time schedules. 
. 
While watching the game it is not in full match 90 minutes or even the extra times or extra time with penalty. 

Most of the times the video will froze or buffering.,

**Comment by kolekan** [comment]
> While watching the soccer the live match connection some how get disconnected. You guys need to improve and fix the problems with the time schedules. . While watching the game it is not in full match 90 minutes or even the extra times or extra time with penalty.
> 
> Most of the times the video will froze or buffering.,

I understand your frustration but take your complaints to the site owners.  The plugin displays what the site provides
