### ISSUE TITLE
bugatsinho sport hd addon not working

### ISSUE THREAD

**Issue by wilmavandekken** [bugatsinho/bugatsinho.github.io#158]
the bugatsinho sport hd addon is not working
i can not watch any dutch soccer games, it is buffering all the time
can you pleesa fix this??

**Comment by bugatsinho** [comment]
> the bugatsinho sport hd addon is not working
> 
> i can not watch any dutch soccer games, it is buffering all the time
> 
> can you pleesa fix this??

Buffering isn't something I can fix. Most of the time has to do with user's end.
