### ISSUE TITLE
ReleaseBB and some suggestion feature :)

### ISSUE THREAD

**Issue by DjDiabolik** [bugatsinho/bugatsinho.github.io#16]
First of all i need to thanks you for brings back in life about a kodi addons for scrapes this site.
After EntertainmentRepo has left the kodi scene there seemed to be no more hope... very greatfull thanks.

About the some suggestion feature...... i have some... for example:
1) Add a News command/buttons. Somethigs for check the current status....... about 2 o 3 days ago whit the latest 1.7.5 i have tryed to use and every section report an errors to me and say to check the kodi log. After from the preferences i see the source site it's rlsbb.to.... i have tryed to open the site from my pc and that mirrors it's offline (now apparently it's work again). For use the addons i have simply swap to rlsbb.tu.
Whit this news commands you can for example create a daily update to user....  you thinks it's usefull ? I hope I explained myself.....

2) The seconds feature it's openload pair........... if you know there's exist a italian kodi addons based on "Pelislacarta" need to scrapes site.
That addons as a particular use....... some site use mirrors on openload and if you choose to reproduce on kodi there's no pair request appairs.... nothings. The reproduction starts on kodi whitout any pair request.
Apparently also if you open an openload links from a pc using firefox or chrome there's no pair request....... it's only a user-agent request ??? mmmmmm.... i thinks not but if if you want to take a look to this addons i can report to you the name and see how it's works the openload sections....

**Comment by bugatsinho** [comment]
thank you for your kind words really appreciate it!
about 1 i will think about it!
about 2 i know the ex-addon pelisalcarta that became alfa addon and they have their own resolver and it isnt that much famous mainstream addon!
SO YOU WONT SEE ANY CODE to bypass openload in my RELEASEBB as im using resolveurl and i have to accept the agreement jsergio and openload owners made time ago.It isnt that hard to open your mobile and pair and have good openload streams for 4 hours!

**Comment by DjDiabolik** [comment]
Ah.. about openload:
so there would be "develop" on resolveurl........I imagined that infact that addons has a internal resolver for every host.

**Comment by bugatsinho** [comment]
> Ah.. about openload:
> so there would be "develop" on resolveurl........I imagined that infact that addons has a internal resolver for every host.

maybe my english isnt good but im sure i said that their using their openload resolver...and i use resolveurl to resolve the links...so in that case and because the addon has many users i will stick with the pairing policy!

**Comment by DjDiabolik** [comment]
Ah ok... About english. No problems for your English............... i have your same problems because and i'm a big fan of Google Translators :)

**Comment by bugatsinho** [comment]
News-Updates added to last update!
