### ISSUE TITLE
Error adding repo 

### ISSUE THREAD

**Issue by jlatorreaguilar** [bugatsinho/bugatsinho.github.io#161]
First thing is to say sorry cause i´m new here and i don´t know if i must open an issue here to share my problem.

I have some errors after installing repo from zip (v2.7) related to the addons that are in the repo. I am in Kodi Omega 21.1.0 but i´ve tried some versions 21.0, 20.5, 20.2, 20.1 and same issue.

Here is the log:

> 2024-10-15 21:35:04.237 T:19200    info <general>: CAddonMgr::ADDON::CAddonMgr::FindAddon: repository.bugatsinho v2.7 installed
> 2024-10-15 21:35:11.685 T:23768   error <general>: Repository add-on repository.magicoGR uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
> 2024-10-15 21:35:11.685 T:23768 warning <general>: Repository add-on repository.magicoGR uses plain HTTP for add-on downloads in path http://romanvm.github.io/kodi_repo/repo - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
> 2024-10-15 21:35:11.685 T:23768   error <general>: Repository add-on repository.twilight0 uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
> 2024-10-15 21:35:11.686 T:23768   error <general>: Repository add-on repository.universalscrapers uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.
> 2024-10-15 21:35:11.686 T:23768   error <general>: Repository add-on repository.universalscrapers does not have any directory matching 21.1.0 and won't be able to update/serve addons! Please fix the addon.xml definition

I´ve tried to reinstall Kodi and clean all the data to do a clean installation, but same issue.

Don´t know if someone else have this problem.

Thanks for your work and time.

**Comment by bugatsinho** [comment]
You don't need to install all others repositories with no reason. Just mine and the addon you want to use😬
