### ISSUE TITLE
Everyday baddest

### ISSUE THREAD

**Issue by ema1986ct** [bugatsinho/bugatsinho.github.io#162]
im a user of   this addon from 3 years ago, some months ago sport hd work great, various hosts and fluid playing, now only 2 hosts,  s2watch never works, and coolrea can play but freezes every 6-7 seconds, and whenever it wants crashes and close playing, what happened to this addon? in this state its practically useless....

**Comment by bugatsinho** [comment]
You are a user of a free addon that gets the links from the website. I don't control the links. So plz do me a favor.... Find other addon cause I don't like ungrateful people
🤐🤐🤐🤐

**Comment by davidoppen** [comment]
I want to add to the bug report but with a more neutral tone. I'm very grateful for your work, between all the other sports-addons I always use yours! 
Nevertheless, I experienced the same issue as ema1986ct, came here to open a new bug-report and saw that it already exists. Unfortunately every time trying the s2watch link it throws a kodi error, the coolrea link always works. Maybe you could consider removing the s2watch option alltogether.

**Comment by bugatsinho** [comment]
Or you can bypass them and use the ones that works for you, until the day I'll find time to fix the addon. So today after the last update s2 links works right?
