### ISSUE TITLE
add ons not working on Kodi

### ISSUE THREAD

**Issue by Trickyhammer** [bugatsinho/bugatsinho.github.io#165]
Hi

New to all this 
Have a new Firestick, uploaded Kodi and some add ons to watch sport
Nothing seems to play, using the crew, sport HD
Have allowed sources and followed tutorials but getting error logs as per attached photo's

Any advice / help would be appreciated

Thanks

![IMG_4466](https://github.com/user-attachments/assets/9c0f2cff-c365-4ece-9fb6-ca4a18792621)

![IMG_4467](https://github.com/user-attachments/assets/22173ddd-7733-40da-8c44-90ef310410f6)

**Comment by bugatsinho** [comment]
Are you sure this is one of my addons?
SportHD menu is like that 
![image](https://github.com/user-attachments/assets/ca2d43ea-8e1f-4780-81fc-26638b726081)
