### ISSUE TITLE
Set View-Types Error

### ISSUE THREAD

**Issue by Apocalypso36** [bugatsinho/bugatsinho.github.io#18]
Every time I select "Big list" as my preferred view-type in ReleaseBB for the "Links" section, it keeps reverting back to its "Thumbnail" default setting. However, when checking View-mode under Settings, I can see my preferred choice (and others that I've selected) reflected in each of their respective View-Type sections. I have re-selected and saved my preferences repeatedly, cleared the cache, all to no avail. Any suggestions? I'm not having this problem in other Kodi addons where I have selected and saved my preferred view-types. Currently using your latest version (1.8.0) on Kodi 18.2.

**Comment by bugatsinho** [comment]
which skin?i tested on aeon nox silvo and i get only  available view types for links LIST/THUMBNAILS

**Comment by Apocalypso36** [comment]
I'm using the Confluence skin.

**Comment by bugatsinho** [comment]
i will check now thanks

**Comment by bugatsinho** [comment]
found the issue pal...
`    view.setView('videos', {'skin.estuary': 55, 'skin.confluence': 500, 'skin.xonfluence': 500})`
for those 3 skins i set some defaults...so you can go line 452 default.py and remove the default for your skin untl i will push the update
https://github.com/bugatsinho/bugatsinho.github.io/blob/45f107ebb10bd74c56ba7da9bd7de2b01d5354b3/plugin.video.releaseBB/default.py#L452

**Comment by Apocalypso36** [comment]
Ok, thanks. This goes way beyond my technical capability, so I will wait until you are able to push that update. I'm a patient man. 🙂

I really appreciate btw you having continued the development of ReleaseBB from the previous developer. It's always been one of my main go-to addons. 👍
