### ISSUE TITLE
Releasebb search

### ISSUE THREAD

**Issue by aconer81** [bugatsinho/bugatsinho.github.io#2]
Hey bud the releasebb addon was working flawlessly till about a few days ago then all of a sudden the search function stopped working whenever I search 4 a movie an error scrolls down from top of screen and returns blank results here is an upload of my log file but I couldn’t see anything from the releasebb addon after I tried a few searches
https://paste.kodi.tv/ijocibuboh 
Thanks 4 any help & all your hard work much appreciated have a good one

**Comment by bugatsinho** [comment]
Happy New Year!
first thank you for taking time to raise an issue but i will need a log file after you populate the error as now your log file is like you open the kodi and then open the kodi log uploader and click upload log!so plz provide another kodi log after you populate the error!

**Comment by bugatsinho** [comment]
@aconer81 so the issue is that the search link changed...i will fix it ASAP.
thank you

**Comment by aconer81** [comment]
Happy new year as well hope u enjoyed the holidays! Thanks 4 the quick reply & ur help plus all the hard work u have put in much appreciated! Just wanted 2 say that i did upload the log file after I tried doing a few searches in the addon but when I checked the log myself I didn’t see any error about the addon dunno y but I’m glad u found the issue thanks
Oh yeah I hope I can ask u a question not related 2 the releasebb addon when I looked at the log file I saw that it had a few errors towards the end saying unknown addon id and it lists a few old addons that I don’t even have installed anymore such as incursion, placenta, covenant, blamo & magicality so I dunno y those errors r coming up would u happen 2 know y those errors pop up nd how 2 get rid of them thanks appreciate any help have a good day

**Comment by bugatsinho** [comment]
looks like you unistalled the addons but not the dependencies they are coming with...

**Comment by aconer81** [comment]
I checked dependencies & it looks like most of the ones that belonged 2 those addons were deleted the only ones left r dependencies that the rest of the addons I have installed use none of the dependacies r orphaned thanks 4 ur help!
I just checked the releasebb addon & the search function is working again thanks 4 the quick fix oh yeah something is up with the version number tho kuz it says that it should’ve updated to version 1.5.1.1 but after it updated it shows that it’s ver 1.5.1 so the addon still shows up in the available updates section saying an update to ver 1.5.1.1 is available!
Anyway thanks 4 all your help & hard work bud
