### ISSUE TITLE
app stopped working this 7/16/19. checked settings. version is right

### ISSUE THREAD

**Issue by harvickern** [bugatsinho/bugatsinho.github.io#20]
I was watching Pawn Stars through the app yesterday. After it was over I clicked on the next show. got the error. has the error ever since no matter what I do. Have checked settings. Rest of apps work fine. just this one is down. My favorite app and the only one that seems to have everything, including reality tv and pro wrestling. I tell everyone who uses Kodi about this amazing app. Just wish I could use it.

**Comment by bugatsinho** [comment]
without a log file, I can't help you sorry

**Comment by harvickern** [comment]
Well that sucks. All it says is check the log but I have no idea where that is on the Freestream. Sucks as I have been using this app since the Streamsmart was worth using.

Sent from my iPhone

On Jul 17, 2019, at 12:25 PM, Bugatsinho <notifications@github.com<mailto:notifications@github.com>> wrote:


without a log file, I can't help you sorry

**Comment by bugatsinho** [comment]
well use better language and educate yourself on how to use and do basic things on Kodi

**Comment by harvickern** [comment]
Really? I compliment your app and tell you I brag about it to others and you act like an asshole? Amazing customer service. Not everyone is an expert at computers and programming. Most dealers who sell these boxes can barely turn them on. I am an older guy who just wants to watch his favorite shows. No reason to be a prick.

Mike Bruns
BLC Web Services
92 Maple Drive
Gorham, Me
04038
207-318-8173
"Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do."
Pele
This e-mail and any attached files contain information for the exclusive use of the individual or entity to who it is addressed and may contain information that is proprietary, privileged, confidential and/or exempt from disclosure under applicable law.  If you are not the intended recipient, you are hereby notified that any viewing, copying, disclosure or distribution of this information may be subject to legal restriction or sanction.  Please notify sender by e-mail or telephone of any unintended recipients and delete the original message without making copies
________________________________
