### ISSUE TITLE
Streams stops after about 5 mins

### ISSUE THREAD

**Issue by robertjanb** [bugatsinho/bugatsinho.github.io#21]
Hi,

Great addon, really love it! Unfortunately, all streams, with all playback services, stop streaming after a few minuters. Tried a lot of things and read through previous threads, but nothing works, so this is my last resort. Main problem seems to be something when this happens:

`[https] Opening 'https://015-49.sport365.tech:43911/ls/c43be5edfb2ff3bead4abe9409f46fe0352817d4f875ca9e2cc9ba438104e9b9/1565111522/5d494fe38e4a6198005907/5tmpp1hrpbom09nn2tdpernk10/5d49b52715fe4/master.m3u8' for reading
2019-08-06 19:18:24.552 T:140314518591232   DEBUG: ffmpeg[7F9D85099700]: [https] HTTP error 553
2019-08-06 19:18:24.557 T:140314518591232   DEBUG: ffmpeg[7F9D85099700]: [hls,applehttp] keepalive request failed for 'https://015-49.sport365.tech:43911/ls/c43be5edfb2ff3bead4abe9409f46fe0352817d4f875ca9e2cc9ba438104e9b9/1565111522/5d494fe38e4a6198005907/5tmpp1hrpbom09nn2tdpernk10/5d49b52715fe4/master.m3u8', retrying with new connection: Server returned 5XX Server Error reply`

Le log:
[https://pastebin.com/ARrfSHrJ](https://pastebin.com/ARrfSHrJ)

Edit: running Kodi 18.3 on Ubuntu Server 18.04 LTS

**Comment by bugatsinho** [comment]
did you test on another device?seems is something with Ubuntu

**Comment by robertjanb** [comment]
Yep, on Raspberry Pi 3 with Raspbian. Same behaviour. I've disabled Pi-Hole
to be sure, no difference alas (did not get any blocked resources, but
wanted to be sure)... I've seen other people struggling as well, did they
use Ad/DNS blocker software?

**Comment by L2501** [comment]
these streams have always been pretty glitchy. they seem to work better when played with a lot of delay using inputstream.adaptive or streamlink (--hls-live-edge 15).  
To use inputstream.adaptive you need a small patch  
```
--- kodi-addon-inputstream-adaptive/src/parser/HLSTree.cpp      2019-08-08 12:01:46.000000000 +0700
+++ kodi-addon-inputstream-adaptive.1/src/parser/HLSTree.cpp    2019-08-08 12:02:37.907210036 +0700
@@ -379,8 +379,7 @@
                 rep->containerType_ = CONTAINERTYPE_MP4;
               else
               {
-                rep->containerType_ = CONTAINERTYPE_INVALID;
-                continue;
+                rep->containerType_ = CONTAINERTYPE_TS;
               }
             }
             else
```

**Comment by drakman70** [comment]
Exactly the same it happens to me.
After about 5 or 6 minutes the stream stops and kicks me out. I couldn't find a solution. However it's my favorite sports addon and I would like to say a big thanks to its creator bugatsino. Bugatsino να σαι καλά φίλε μου...

**Comment by bugatsinho** [comment]
@drakman70 έχεις και εσύ Ubuntu?
now the issue is known and for that reason the add-on has 3 types of playback using inputstream streamlink and f4m with which of those 3 do you have the issue?did you try them all?also test on website if the stream goes down too after six minutes!maybe isn't add-on issue at all

**Comment by drakman70** [comment]
Όχι δεν έχω Ubuntu. 
I have tried it in three different tv boxes running libreelec coreelec and recently on my android xiaomi mibox. The same behavior to all of them. I have also used all of those 3 playback methods with the same results. Sometimes it plays for longer time around 8-9 minutes but nothing more than this. Then kicks me out. Η αλήθεια είναι ότι δεν εχω δοκιμάσει από το site τους. I will try to play a stream from their site and I will keep you informed.

**Comment by drakman70** [comment]
Φίλε μου bugatsino, 
When I stream from their site there's no problem. Ι used 3 different links without link drops. The next step is to try to install Kodi on my windows pc and see if it has the same behavior.

**Comment by bugatsinho** [comment]
@drakman70 I hope now you will understand....
using inputstream

![sport365](https://user-images.githubusercontent.com/18536253/64483832-350d2480-d1cf-11e9-833d-2b1209410bab.png)
