### ISSUE TITLE
Update failed v2.6.3.1

### ISSUE THREAD

**Issue by stavro-gh** [bugatsinho/bugatsinho.github.io#22]
running libreelec 9.1.501 / kodi 18.4
getting update failed

**Comment by bugatsinho** [comment]
fixed

**Comment by stavro-gh** [comment]
fixed in which version?
i can not update from v2.6.3 to v2.6.3.1 nor install v2.6.3.1 after uninstall v2.6.3
hardware: rpi3
software. libreelec 9.1.501
