### ISSUE TITLE
utf8 decode error

### ISSUE THREAD

**Issue by naude-r** [bugatsinho/bugatsinho.github.io#23]
some streams contain invalid utf8 characters, which trips up the json decoder. this still on kodi 17

> Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'utf8' codec can't decode byte 0x80 in position 1: invalid start byte
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/main.py", line 492, in <module>
                                                get_streams_play(params)
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/main.py", line 71, in get_streams_play
                                                addLinkItem(frame.get('title', ''), json.dumps(frame), mode='take_stream',
                                              File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
                                              File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
                                              File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 1: invalid start byte
11:55:49.268 T:548347641856   ERROR: GetDirectory - Error getting plugin://plugin.video.sport365.live/?ex_link=http%3a%2f%2fwww.s365.live%2fen%2flinks%2f5d85e7b70e206768842119%2f1%40%5b%5d&foldername=%5bCOLOR%20lightgreen%5d%e2%80%a2%5b%
2fCOLOR%5d11%3a45%3a%20%5bCOLOR%20blue%5dNew%20Zealand%20-%20South%20Africa%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dEnglish-HQ%5b%2fCOLOR%5d%2c%20Rugby%20World%20-%20World%20Cup&mode=get_streams_play&params=%7b%27_service%27%3a%20%27sport365%2
7%2c%20%27_act%27%3a%20%27ListChannels%27%2c%20%27_url%27%3a%20%27http%3a%2f%2fwww.s365.live%2f%27%2c%20%27title%27%3a%20%27%5bCOLOR%20lightgreen%5d%5cxe2%5cx80%5cxa2%5b%2fCOLOR%5d11%3a45%3a%20%5bCOLOR%20blue%5dNew%20Zealand%20-%20South%
20Africa%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dEnglish-HQ%5b%2fCOLOR%5d%2c%20Rugby%20World%20-%20World%20Cup%27%7d

**Comment by gabglus** [comment]
Hi,
The same problem after the last update

11:49:40.330 T:140054580160256   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'utf8' codec can't decode byte 0xf9 in position 1: invalid start byte
                                            Traceback (most recent call last):
                                              File "/home/XXX/.kodi/addons/plugin.video.sport365.live/main.py", line 492, in <module>
                                                get_streams_play(params)
                                              File "/home/XXX/.kodi/addons/plugin.video.sport365.live/main.py", line 71, in get_streams_play
                                                addLinkItem(frame.get('title', ''), json.dumps(frame), mode='take_stream',
                                              File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
                                                return _default_encoder.encode(obj)
                                              File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
                                                chunks = self.iterencode(o, _one_shot=True)
                                              File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
                                                return _iterencode(o, 0)
                                            UnicodeDecodeError: 'utf8' codec can't decode byte 0xf9 in position 1: invalid start byte
                                            -->End of Python script error report<--
11:49:40.380 T:140057660084160   ERROR: GetDirectory - Error getting plugin://plugin.video.sport365.live/?ex_link=http%3a%2f%2fwww.sport365.sx%2fen%2flinks%2f5d93028ee7166167590641%2f1%40&foldername=%5bCOLOR%20lightgreen%5d%e2%80%a2%5b%2fCOLOR%5d10%3a00%3a%20%5bCOLOR%20blue%5dATP%20Beijing%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dHQ%26nbsp%3b-SD%5b%2fCOLOR%5d%2c%20Tennis%20China%20-%20ATP%20Beijing%20-%20Hard&mode=get_streams_play&params=%7b%27_service%27%3a%20%27sport365%27%2c%20%27_act%27%3a%20%27ListChannels%27%2c%20%27_url%27%3a%20%27http%3a%2f%2fwww.sport365.sx%2f%27%2c%20%27title%27%3a%20%27%5bCOLOR%20lightgreen%5d%5cxe2%5cx80%5cxa2%5b%2fCOLOR%5d10%3a00%3a%20%5bCOLOR%20blue%5dATP%20Beijing%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dHQ%26nbsp%3b-SD%5b%2fCOLOR%5d%2c%20Tennis%20China%20-%20ATP%20Beijing%20-%20Hard%27%7d
11:49:40.381 T:140057660084160   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sport365.live/?ex_link=http%3a%2f%2fwww.sport365.sx%2fen%2flinks%2f5d93028ee7166167590641%2f1%40&foldername=%5bCOLOR%20lightgreen%5d%e2%80%a2%5b%2fCOLOR%5d10%3a00%3a%20%5bCOLOR%20blue%5dATP%20Beijing%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dHQ%26nbsp%3b-SD%5b%2fCOLOR%5d%2c%20Tennis%20China%20-%20ATP%20Beijing%20-%20Hard&mode=get_streams_play&params=%7b%27_service%27%3a%20%27sport365%27%2c%20%27_act%27%3a%20%27ListChannels%27%2c%20%27_url%27%3a%20%27http%3a%2f%2fwww.sport365.sx%2f%27%2c%20%27title%27%3a%20%27%5bCOLOR%20lightgreen%5d%5cxe2%5cx80%5cxa2%5b%2fCOLOR%5d10%3a00%3a%20%5bCOLOR%20blue%5dATP%20Beijing%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dHQ%26nbsp%3b-SD%5b%2fCOLOR%5d%2c%20Tennis%20China%20-%20ATP%20Beijing%20-%20Hard%27%7d) failed
