### ISSUE TITLE
sport365

### ISSUE THREAD

**Issue by LEWZAC** [bugatsinho/bugatsinho.github.io#27]
I have inputstream adaptive, and inputstream RTMP enabled in kodi, but 365 keeps giving me error messages when i attempt to stream anything ie football. when i go to settings in 365 it asks me to enable them both but will not let me why ?

**Comment by bugatsinho** [comment]
the add-on doesn't work cause of changes in the website! they encrypted the streams  differently and Im looking for solution!

**Comment by LEWZAC** [comment]
thanks very much for the info, at least i know why now, thanks again

------ Original Message ------
