### ISSUE TITLE
sport365 error

### ISSUE THREAD

**Issue by ekikos** [bugatsinho/bugatsinho.github.io#28]
hi,

i am using soprt 365 version 2.6.3.1. for some reason in the past 2 weeks i can no longer view any stream.  attached is the kogi log.
i will highly appreciate you feedback.
Thanks,
ekikos
[kodi.log](https://github.com/bugatsinho/bugatsinho.github.io/files/3692931/kodi.log)

**Comment by drakman70** [comment]
If you read carefully as the creator wrote the add-on doesn't work cause of changes in the website! they encrypted the streams differently and he is looking for solution!

You are not the only one with this problem...

**Comment by RickyVaughn99** [comment]
Actual 2.6.4 works for me.
Also the links seem to load quicker and the quality seems improved.
Great job! Thanks ! Keep up the bombastic work.
Cheers,

RV.

**Comment by RickyVaughn99** [comment]
Update:

Same error as before.
[Log](https://paste.kodi.tv/awohaxalaz.kodi).
Cheers,

RV.

**Comment by HenioH** [comment]
Updated to 2.6.4 and was able to get one game to play for a few mins then it closed. I have not been successful playing any other game in the 2.6.4 after that. Tried with and without a vpn to no success. When I click on any game then any link 1-6 its acts like its going to open then nothing. Anyone having this issue?

**Comment by bugatsinho** [comment]
@HenioH  that issue means that you are blocked from the website...

**Comment by HenioH** [comment]
> @RickyVaughn99 @HenioH that issue means that you are blocked from the website...

Is this common? What is the lifespan using a new IP within the new update? Tried a new IP and after 2 mins game cut off. Also with a vpn on last only a couple mins then cant open games again.

**Comment by HenioH** [comment]
> @RickyVaughn99 @HenioH that issue means that you are blocked from the website...

Is this common? What is the lifespan using a new IP within the new update? Tried a new IP and after 2 mins game cut off. Also with a vpn on last only a couple mins then cant open games again.

**Comment by Last-Dance-Official** [comment]
@bugatsinho 

it was working after last update but now dont work anymore and getting follow error:

16:43:59.211 T:545981026528   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/main.py", line 438, in <module>
                                                get_streams_play(params)
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/main.py", line 70, in get_streams_play
                                                frames = mod.getStreams(ex_link)
                                              File "/storage/.kodi/addons/plugin.video.sport365.live/sport365.py", line 113, in getStreams
                                                enc_data=json.loads(base64.b64decode(s))
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--

**Comment by stavro-gh** [comment]
same here, worked for me the very first time after the update to 2.6.4 weeks ago and then never again.
no difference if i use vpn (tried severel different providers) or not. can this really be related to ip blocking ? the error recurs at the moment the stream links should be retrieved.
