### ISSUE TITLE
sport365

### ISSUE THREAD

**Issue by lechu319** [bugatsinho/bugatsinho.github.io#32]
fix sport365 ver 2.6.6.2 - does it work to someone ?

**Comment by stavro-gh** [comment]
not for me. most of the links don't work at all. a view are starting but stopping after some seconds.
with or without vpn

**Comment by bugatsinho** [comment]
DID YOU USED F4M playback before you opened the issue?

**Comment by stavro-gh** [comment]
sorry did not know that we have to switch from imputstream to f4m.
with vpn and f4m it works now for me. thanx a lot.
