### ISSUE TITLE
AuraMod landscape-art and widget problem

### ISSUE THREAD

**Issue by DaisyF8** [bugatsinho/bugatsinho.github.io#35]
Hi Bugatshinho,

thx for this addon. It's I think the fastest around for gathering scene-releases.

Also, this post got larger than I first thaught.  Don't mean to overwhelm you with all these details. Your addon works good :D

In AuraMod most of the landscape art for TV and Movie only displays your ReleaseBB icon.  See here for TV :

<a href="https://ibb.co/Rzz8HHm"><img src="https://i.ibb.co/Rzz8HHm/screenshot000.png" alt="screenshot000" border="0"></a> <a href="https://ibb.co/4K3DKFJ"><img src="https://i.ibb.co/4K3DKFJ/screenshot000.png" alt="screenshot000" border="0"></a> <a href="https://ibb.co/zJ5nWg6"><img src="https://i.ibb.co/zJ5nWg6/screenshot001.png" alt="screenshot001" border="0"></a> <a href="https://ibb.co/tsfQC44"><img src="https://i.ibb.co/tsfQC44/screenshot002.png" alt="screenshot002" border="0"></a> <a href="https://ibb.co/sQVCygX"><img src="https://i.ibb.co/sQVCygX/screenshot003.png" alt="screenshot003" border="0"></a> <a href="https://ibb.co/XpMpd4L"><img src="https://i.ibb.co/XpMpd4L/screenshot004.png" alt="screenshot004" border="0"></a> <a href="https://ibb.co/jvcdKSn"><img src="https://i.ibb.co/jvcdKSn/screenshot005.png" alt="screenshot005" border="0"></a> <a href="https://ibb.co/d6cmv1r"><img src="https://i.ibb.co/d6cmv1r/screenshot006.png" alt="screenshot006" border="0"></a> <a href="https://ibb.co/4KZVJtG"><img src="https://i.ibb.co/4KZVJtG/screenshot008.png" alt="screenshot008" border="0"></a>

I can set viewtypes, and they are remembered (sometimes hardcoded defaults ? not here).  But I want to use view type landscapepanel and I only see the icon.

**Comment by DaisyF8** [comment]
Also, "TV Packs" provides a good poster, but "TV Shows"  only provides a Banner, which gets cropped when you display Poster

**Comment by DaisyF8** [comment]
And "Recommended Movies" doesn't have meta-data, where "TOP" does. Both widgets are on type posterdetails.

https://ibb.co/p205WWT
https://ibb.co/yWKZFdm

**Comment by bugatsinho** [comment]
DID you ever see on releasebb website METADATA? this addon doesn't use metadata, as exodus-forks, is grabbing only the icons-posters the website provides.Thank you!

**Comment by DaisyF8** [comment]
Hey, let's make this a teaching moment for me then ? What do you say ? It'll be fun !

Only look at my last remark (third post, about TOP and Recommenden Movies) : what works with the one should work with the other.

Problem is your coding, or not ?

Kisses, your welcome.

PS : [Heart and Valve disease is serious, get informed.](https://www.medicinenet.com/heart_valve_disease/article.htm)
