### ISSUE TITLE
A small bug on the "news - updates" window

### ISSUE THREAD

**Issue by pitsi** [bugatsinho/bugatsinho.github.io#37]
When clicking the "github link" button, the web browser opens this address
`https://github.com/bugatsinho/bugatsinho.github.io/tree/master/plugin.video.releaseBB`
which is for releasebb, instead of this one
`https://github.com/bugatsinho/bugatsinho.github.io/tree/master/plugin.video.sport365.live`
which is for sport365. With a quick view at the code, this is on line 65 of newsbox.py, here
https://github.com/bugatsinho/bugatsinho.github.io/blob/master/plugin.video.sport365.live/newsbox.py#L65

Also, a few lines lower, at line 73 of the same file, there is a commented-out url link that leads here
`https://pastebin.com/raw/mpgxNy2V`
which is also releasebb related, so it can be removed.

Thank you

**Comment by bugatsinho** [comment]
Thank you for that I will fix ASAP!
Also, words and code after '#' sign do nothing as they are only as a comment!
instead, check the URL on this line
https://github.com/bugatsinho/bugatsinho.github.io/blob/9c7b2c0f58847182c1f4c44d99e44d532cbafc6f/plugin.video.sport365.live/newsbox.py#L131

**Comment by bugatsinho** [comment]
FIXED https://github.com/bugatsinho/bugatsinho.github.io/commit/b1bcfe486729011fc0eb998804949312f70dee5d

**Comment by pitsi** [comment]
I know what comments are and that whatever lies beyond the "3" is not used. I just mentioned that it is about releasebb too.
