### ISSUE TITLE
ReleaseBB - ClickNUpload.org Captcha.... it's works ?

### ISSUE THREAD

**Issue by DjDiabolik** [bugatsinho/bugatsinho.github.io#43]
For the ReleaseBB addons:

For some show sometime i see it's be used this............ When i first time select one mirros i never seen before.
I obtain on screen a selection from image...... like a Google Captcha, i need to select all image of hills or somethings. After first selection i obtain an errors to reproduce and report me to see the log of kodi.

Have you add this feature in parts ?? It's a new feature not completely working ?

**Comment by bugatsinho** [comment]
is this an issue or a suggestion? i don't understand I'm sorry

**Comment by DjDiabolik** [comment]
It's somethigs like feature / feedback report :)
It's about one of clicknupload mirrors......
When you choose one of hit you obtain a request like a captcha on tv...... it's say usually one or two but after first it's appears an errors say to read kodi log.

**Comment by bugatsinho** [comment]
i will check them. thank you

**Comment by DjDiabolik** [comment]
oh exactly... if you addons will "pass" the link to "urlresolver" probably this module need to be develop to support the captcha.
little OT:
Oh wait... urlresolver or resolverurl you use ? resolveurs it's maintainer by jsergio123...... urlresolver (the most popular) apparently it's developer from TVA whit all s**t recently like indigo put as dependency....

**Comment by bugatsinho** [comment]
listen mate! the module works perfect only issue is that many people uploading files that we can stream like zip and rar!! that is the issue!nothing to do with that and so the issue is closed
![image](https://user-images.githubusercontent.com/18536253/73032016-c80bcb80-3e0b-11ea-9701-c798152456d6.png)

**Comment by DjDiabolik** [comment]
No man... you WRONG!
Look here:
https://clicknupload.org/3h25ewnrzap2

It's a MP4 files..... and it's request the CAPTCHA.

Same file also here:
https://clicknupload.org/wp042vrfn0zc/WWE.Monday.Night.Raw.2020.01.20.HDTV.x264-NWCHD.mp4.html

I have tryed to watch it from my OSMC....... it's the captcha appears on my tv. I can select and pass first question and after that...... say to read my log.

It's a my issue ? You can reproduce this ?

**Comment by bugatsinho** [comment]
are you using premium service?

**Comment by DjDiabolik** [comment]
Lol thanks :)
