### ISSUE TITLE
ReleaseBB need some fix ? All result it's show as empty.....

### ISSUE THREAD

**Issue by DjDiabolik** [bugatsinho/bugatsinho.github.io#48]
I have right now try to see a show from using ReleaseBB 1.8.6 on latest OSMC stable image.

I have try to reach this... at the moment it's the first of TvShow:
http://rlsbb.to/secrets-of-our-cities-s02e02-720p-hdtv-x264-cbfm/

From the comment, apparently, there's many avaible links watchable by kodi... there's present various "ClicknUpload" mirrors for example this:
https://clicknupload.co/ljavbng9s1yh

Apparently it's a valid MKV mirrors but how i already sayd when you open this show you not obtain result.... completely empty list.

I have also tryed a lot old show... like this:
http://rlsbb.ru/wwe-friday-night-smackdown-2020-03-06-hdtv-x264-nwchd/

Also here... on comment there's some ClicknUpload mirrors avaible like this:
https://clicknupload.co/9233cl3q6s74

If i remember also a waaw.tv source it's reachable by ResolveURL like here:
https://waaw.tv/watch_video.php?v=eUvz0a6p0u1R
This is also listed on comments... not appearas in result list.

But also here...... the result list it's be show completely empty.

It's a my issue ? You can check if you have a similar issue ?

**Comment by bugatsinho** [comment]
waaw.tv links cant be resolved as they have invisible recaptcha! if links dont work means that resolver has issues or links are dead..nothing to do with the addon!

**Comment by DjDiabolik** [comment]
nothing to do with the addon ? Really ? And because the clicknupload not appears on result ? If i remember it's correctly supported.
