### ISSUE TITLE
ReleaseBB Kodi not loading anything 

### ISSUE THREAD

**Issue by Dell2248** [bugatsinho/bugatsinho.github.io#49]
Since April 21 we have not been able to load ReleaseBB on our Kodi it always says something went wrong and to check the log. If you click on ReleaseBB TV shows nothing is brought up.

**Comment by johndeere69** [comment]
Have you figured out the issue, i love exploring release bb ?

**Comment by Dell2248** [comment]
It was fixed and now it’s down again because of a cloud scraper or something. 

Thanks 

Danielle Shebagegit
