### ISSUE TITLE
Ability to modify Domain

### ISSUE THREAD

**Issue by thomfam** [bugatsinho/bugatsinho.github.io#53]
None of the supplied ReleaseBB Domains are accessible for me.  RELEASEBB.UNBLOCKIT.ONE isn't working for me but RELEASEBB.UNBLOCKIT.ME does work.  Would then mean I could use this addon if I could modify .ONE to .ME

**Comment by bugatsinho** [comment]
add-on doesnt work. Needs cloudscraper update.
