### ISSUE TITLE
Rlsbb info request 

### ISSUE THREAD

**Issue by Pawman63** [bugatsinho/bugatsinho.github.io#54]
Just really a question is it likely that the addon rlsbb will be fixed going forward.
I appreciate that you may well be busy with other issues but would be useful to know if the project itself is moving forward.

**Comment by bugatsinho** [comment]
The addon depends on another addon called cloudscraper! https://github.com/bugatsinho/bugatsinho.github.io/blob/80b141a8034a3f3cbcfb68042611a8a3a56efaaa/plugin.video.releaseBB/addon.xml#L4
Cloudscraper addon is the one that helps releasebb addon to bypass cloudflare protection on the website and get the data.
So we are waiting for a cloudscraper update.

**Comment by PaulRBoon** [comment]
I thought the cloudscraper addon had been updated and was on version 1.2.36 currently

**Comment by bugatsinho** [comment]
@PaulRBoon but it doesn't work for all websites

**Comment by PaulRBoon** [comment]
OK cool, well not cool and full understand now thanks for the great work my friend
