### ISSUE TITLE
Xenon App issue

### ISSUE THREAD

**Issue by VLH300** [bugatsinho/bugatsinho.github.io#60]
One of my favorite Kodi apps was "Skyline Webcams". This app ran very well prior to the Kodi 18.9 upgrade. Now, I get nothing but error messages whenever I try to access the app.

I'm using Nvidia Shield TV Pro - Running Kodi 18.9 - Xenon Plus version 4.1
I use Express VPN service and I subscribe to Real Debrid

I'm also Running Kodi 18.9 and Xenon Plus version 4.1 on two different laptops and I have the same issue.

Perhaps, it is a simple fix. If so, I would appreciate some advice. Thanks 👍

**Comment by bugatsinho** [comment]
Sorry for the late reply @VLH300 . I had a conversation in twitter with the website owner about not use illegal addon to watch the cams but use the website! 
So after that I'm not sure if i want to update the addon.
https://twitter.com/RubenSambora/status/1326849429446537217

**Comment by bugatsinho** [comment]
https://github.com/bugatsinho/bugatsinho.github.io/commit/cde6b05882e465b2d8a7102c1c801e3e6693cb8a
