### ISSUE TITLE
Release BB domains 

### ISSUE THREAD

**Issue by ieswideopen** [bugatsinho/bugatsinho.github.io#61]
It appears for me that none  of the domains are working at present. Recent issue.

**Comment by Pawman63** [comment]
Yes I take it its a cloudscaper issue as results are not being pulled from rlsbb via debrid, not sure if the addon can be gerryrigged with another unblocked as a stop gap.

**Comment by DjDiabolik** [comment]
cloudflare it's now present if all mirror............ all addons it's not anymore works.
until some weeks ago the cloudflare it's only on search feature...... recently the proxybb it's works but now nothigs works.

Mark this as double request:
https://github.com/bugatsinho/bugatsinho.github.io/issues/55

**Comment by pitsi** [comment]
So, my kodi just started to pop a notification saying "releasebb has crashed", on every start and these are shown in the log
```
2021-01-05 08:29:29.196 T:140662578075392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.releaseBB/service.py", line 23, in <module>
                                                fline = set_line.format(domains[0], domains[1], domains[2], domains[3], domains[0])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
```
It may be unrelated to the issue mentioned here, but since it mentions the domains, I thought I should mention it here.
Libreelec 9.2.6 x64 with kodi 18.9.

**Comment by DjDiabolik** [comment]
Same Error - my OSMC on my Rasp Pi2 setup. When i boot i obtain an errors on log appears this:
[code]
2021-01-06 13:15:33.663 T:1625776352   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.releaseBB/service.py", line 23, in <module>
                                                fline = set_line.format(domains[0], domains[1], domains[2], domains[3], domains[0])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
[/code]
How it's need this service.py ??

@bugatsinho

**Comment by pitsi** [comment]
Today's upgrade to 2.0.3.1 fixes the startup issue.
The domains issue remains though.

**Comment by bugatsinho** [comment]
morning guys @DjDiabolik @pitsi the code is needed to get the available eztv domains. from this domain https://eztvstatus.com it was down lately and that was creating the issue. now is back again and i will update the service.py
