### ISSUE TITLE
Not working again

### ISSUE THREAD

**Issue by TommyGunn69** [bugatsinho/bugatsinho.github.io#62]
Hi, was working with the new update now not working again on any of the domains, but the domains work in a web browser so the actual domains are working .

**Comment by bugatsinho** [comment]
THe domains are working TRUE. when you go to the website did you see that ?
![image](https://user-images.githubusercontent.com/18536253/105052584-0e573300-5a3e-11eb-8f2c-2da2fd11fa49.png)

if yes that means that website is under cloudflare protection and addon can't bypass it to get the source code of the website...

**Comment by TommyGunn69** [comment]
Yes that is it when you go to the websites direct
