### ISSUE TITLE
More of the same

### ISSUE THREAD

**Issue by Pawman63** [bugatsinho/bugatsinho.github.io#63]
Once again all rlsbb down, I understand of course that this is most likely to be a cloudscraper issue but whomever is dealing with that seems not to be doing that right now. I wonder if old cloudscraper updates might work but have no way of getting old versions and testing.
Do you have a way of integration of a cloud scrape in the addon itself.

**Comment by bugatsinho** [comment]
why do you believe that an old version will work?

**Comment by bugatsinho** [comment]
do your tests by using whatever old version you want!!! Good luck
https://github.com/bugatsinho/bugatsinho.github.io/tree/master/_zips/script.module.cloudscraper
