### ISSUE TITLE
releasebb player

### ISSUE THREAD

**Issue by sota1977** [bugatsinho/bugatsinho.github.io#65]
Hello

thanks for the awesome addon!
One suggestion, is there any chance to include releasebb as a player?

**Comment by bugatsinho** [comment]
include releasebb player where?

**Comment by sota1977** [comment]
to be included as a meta player in open meta or other addons like that
thanks

**Comment by bugatsinho** [comment]
this is something that you have to ask open dev to do it!
thank you
