### ISSUE TITLE
Clickupload.com links not working

### ISSUE THREAD

**Issue by Lynn-Marie66** [bugatsinho/bugatsinho.github.io#66]
Getting sometimes up 600 links mainly clickupload they start to connect then stop really don’t no how to sort this so if any one is having same issue please tell me what to do driving me mad it’s been doing it for 2days now the only other link that comes up aparat but maybe 2 links but only sometimes works 😩

**Comment by bugatsinho** [comment]
this is an addon that works with DEBRID service. buy one

**Comment by Lynn-Marie66** [comment]
I’m sorry not everyone can afford to buy I’ve been using releasebb for a long time & recommend this add on to many people I use digzz free so would of been nice of u not to have been so rude!

**Comment by bugatsinho** [comment]
good for you! glad you are using another addon!
