### ISSUE TITLE
ReleaseBB compatability with Kodi 19 'Matrix'

### ISSUE THREAD

**Issue by sb2780** [bugatsinho/bugatsinho.github.io#67]
Kodi update to Matrix disabled ReleaseBB addon as incompatible. Will this be fixed in an upcoming update, or do I need to go back to Kodi Leia?

**Comment by bugatsinho** [comment]
I need to find some time to do it. Until then you should go back to Leia version or use a fork.

**Comment by bugatsinho** [comment]
ReleaseBB 2.1.1 version is now compatible with Kodi19!

**Comment by sb2780** [comment]
This is great news! Thank you!
