### ISSUE TITLE
Correction required to avoid errors

### ISSUE THREAD

**Issue by ozooha** [bugatsinho/bugatsinho.github.io#69]
I apologize I did not know how else to point out these likely errors which required fixing.
They are denoted using _FIX THIS LINE_ :

resources/lib/modules/client.py
```
def replaceHTMLCodes(txt):
    # txt = re.sub("(&#[0-9]+)([^;^0-9]+)", "\\1;\\2", txt)
    txt = HTMLParser.unescape(txt) # FIX THIS LINE
    txt = txt.replace("&quot;", "\"")
    txt = txt.replace("&amp;", "&")
    txt = txt.replace("&lt;", "<")
    txt = txt.replace("&gt;", ">")
    txt = txt.strip()
    return txt
```
resources/lib/modules/search.py
```
def Search_bb(url):
    if 'new' == url:
        keyboard = xbmc.Keyboard()
        keyboard.setHeading(control.lang(32002).encode('utf-8'))
        keyboard.doModal()
        if keyboard.isConfirmed():
            _query = keyboard.getText()
            query = _query.encode('utf-8')
            try:
                query = quote_plus(query)
                referer_link = 'http://search.proxybb.com?s={0}'.format(query)

                url = 'http://search.proxybb.com/Home/GetPost?phrase={0}&pindex=1&content=true&type=Simple&rad=0.{1}'
                url = url.format(query, random.randint(33333333333333333, 99999999999999999))
                #########save in Database#########
                if six.PY2:
                    term = unquote_plus(query).decode('utf-8')
                else:
                    term = unquote_plus(query)

                dbcon = database.connect(control.searchFile)
                dbcur = dbcon.cursor()
                dbcur.execute("DELETE FROM Search WHERE search = ?", (term,))
                dbcur.execute("INSERT INTO Search VALUES (?,?)", (url, term))
                dbcon.commit()
                dbcur.close()

                #########search in website#########
                headers = {'Referer': referer_link,
                           'X-Requested-With': 'XMLHttpRequest'}
                first = client.request(referer_link, headers=headers)
                xbmc.sleep(10)
                html = client.request(url, headers=headers)
                posts = json.loads(html)['results']
                posts = [(i['post_name'], i['post_title'], i['post_content'], i['domain']) for i in posts if i]
                for movieUrl, title, infos, domain in posts:
                    if not 'imdb.com/title' in infos:
                        continue
                    base = BASE_URL if 'old' not in domain else OLD_URL
                    movieUrl = urljoin(base, movieUrl) if not movieUrl.startswith('http') else movieUrl
                    # title = title.encode('utf-8') #FIX THIS LINE
                    infos = infos.replace('\\', '')
```
plugin.video.releaseBB/default.py
```
def GetLinks(section, url, img, plot):  # Get Links
    try:
        import resolveurl
        from resources.lib.modules import init
        # html = response_html(url, '3')
        html = cloudflare_mode(url)
        listitem = GetMediaInfo(html)
        name = '%s (%s)' % (listitem[0], listitem[1])
        main = list()
        try:
            main = client.parseDOM(html, 'div', {'class': 'postContent'})
        except IndexError:
            pass
        main = [i for i in main if i]
        comments = dom.parse_dom(html, 'div', {'class': re.compile('content')})
        main += [i.content for i in comments if i]
        links = []
        for item in main:
            frames = client.parseDOM(item, 'a', ret='href')
            for url in frames:
                host = GetDomain(url)
                if 'Unknown' in host:
                    continue
                # ignore .rar files
                if any(x in url.lower() for x in ['.rar.', '.zip.', '.iso.']) \
                        or any(url.lower().endswith(x) for x in ['.rar', '.zip', '.iso']):
                    continue
                if any(x in url.lower() for x in ['sample', 'zippyshare']):
                    continue
                # remove any files which do not have these video file extensions #FIX THIS LINE
                if url.rpartition('/')[2].split('.')[-1] not in ['mkv','avi','mp4']: #FIX THIS LINE
                    continue         #FIX THIS LINE
```
Thanks for your good work.
Cheers,
OZooHA

**Comment by bugatsinho** [comment]
thank you for your feedback! Can you plz explain me which is the issue with the line that i use to filter the links by mkv, avi, mp4 ?

**Comment by ozooha** [comment]
Sorry in this instance you dont have to fix the line. You have to just add the if filter of mkv, mp4 and avi before the for loop. 
This if filter removes any hoster site links without any movie files i.e. mkv, avi and mp4 attached to them.

**Comment by ozooha** [comment]
You mean, for example like these below:

``
https://dropapk.to/kb1qjnel2vrf/NOTW21Bx.part1.rar.html
https://dropapk.to/icgjlzwb1yni/NOTW21Bx.part2.rar.html
https://dropapk.to/saiw2ctjnn74/NOTW21Bx.part3.rar.html
``

**Comment by bugatsinho** [comment]
> You mean, for example like these below:
> 
> `https://dropapk.to/kb1qjnel2vrf/NOTW21Bx.part1.rar.html https://dropapk.to/icgjlzwb1yni/NOTW21Bx.part2.rar.html https://dropapk.to/saiw2ctjnn74/NOTW21Bx.part3.rar.html`

no actually i have filter for that .rar.

**Comment by ozooha** [comment]
Ok, forgive me for being dense, can you then explain what you meant earlier?

**Comment by ozooha** [comment]
I have attached a copy of an old version of your [default.py ](https://pixeldrain.com/u/7WGHgGSp)code.

- In it I have tried to address the filter issue which seems to be working fine on my end. The lines to look for is 404 which relies on line 752. The idea being that it looks only for relevant media file extensions for a bunch of resolutions and ignores any of the unwanted non-media rar, iso etc extensions. This seems to work well but you can make the call on this.
- I have used a sort mechanism on line 445 which references line 34. (You can ignore this if you don't like it)
- The _GetPack_ on line 277 extracts TV packs (which are essentially protected links) by moving on to _GetLinkPacks_ at 310 to extract them. I have gotten round this by using the try catch mechanism, which upon failing in _GetLinkPacks_  uses the _GetLinks_ at 368 from 361. This works for me now well but you might have better way to handle this issue with  _GetPack_ and _GetLinkPacks_.

Please feel free to ignore them since you have a better picture how you want your code to function but I thought I would share and help out in a small way.
Thanks again for your work.
Cheers
OZooHA

**Comment by bugatsinho** [comment]
plz share the modded default.py you have, for have a better look on it.

**Comment by ozooha** [comment]
It's was attached ias a link in the message. It is still available coz i just checked.

**Comment by bugatsinho** [comment]
Hi mate, I'm really so sorry to forget this issue and your recommendation, is that code still valid?

**Comment by ozooha** [comment]
No worries.
Forget them as they are not valid anymore.
