### ISSUE TITLE
AFL should be in the Football section

### ISSUE THREAD

**Issue by SpitFire-666** [bugatsinho/bugatsinho.github.io#72]
Hi, I was stoked to be able watch an AFL game through your addon as I couldn't find a stream anywhere else!

Just a suggestion - can we place AFL under the Football section instead of Rugby? Many fans would be offended by it being called rugby 😁

Another thought - maybe it would be better to have categories like AFL, NBA, NRL, instead of the type of sport?

**Comment by campbellkerr** [comment]
My partner just had a good point - rugby is a type of football too!

**Comment by bugatsinho** [comment]
go to the website that my add-on gets the data and do your suggestions.
