### ISSUE TITLE
Skyline Webcams 0.2.1 on Kodi Leia not working

### ISSUE THREAD

**Issue by Max11223344** [bugatsinho/bugatsinho.github.io#75]
Starting Skyline Webcams i can see the selection menu.
Klicking on any cam-link there is only a white screen telling me: Skyline Webcams.com ....

**Comment by theghostofelvis** [comment]
Here the same on Kodi Leia Version 18.3! I love this plugin and it would be great if there will be an update which solves this problem !

**Comment by Collabsvito** [comment]
@bugatsinho 

**Sometimes the readed (Stream-)Link on the webpage is not correct:**

`2021-06-30 13:56:02.545 T:9400  NOTICE: URLLLL: https://www.skylinewebcams.com/de/webcam/italia/lazio/roma/roma-colosseo.html`
`2021-06-30 13:56:02.731 T:9400  NOTICE: LINKKKK: livee.m3u8?a=oj81r1f0mgsrdpps7vip66pd67`
So if I remove the double "e" from "livee" to "live" everything works as expected !!!

I changed Line 243 in your default.py to:
`            link = 'https://hd-auth.skylinewebcams.com/' + str(link.replace('livee.m3u8', 'live.m3u8'))` 

and all fine. :v:
regards

**Comment by bugatsinho** [comment]
@Collabsvito  You are right. i was already to push the update!
![image](https://user-images.githubusercontent.com/18536253/123965472-19fa3e80-d97a-11eb-98ff-0b8385f664b3.png)

**Comment by Max11223344** [comment]
Thank you, Bugatsinho,

the update to Version 0.2.2 made the cams work again :-)
I still have one question: selecting 'greek live cams' from the menu shows me a list of greek cams (written in greek characters),
but selecting any of these cams shows nothing ... no reaction ...
Is there a chance to get these cams working too ?

Regards
Max

**Comment by theghostofelvis** [comment]
Thank You for the fast update , i love these livecams :)

**Comment by Max11223344** [comment]
Watching as many cams as possible i found, that nearly all cams (selecting cams by country) of the United States -except the first 12 cams - show the error Type: <type 'exceptions.IndexError'> Error contents: list index out of range.

This is not only the case with the United States cam ... but here the most cams show this error
