### ISSUE TITLE
SportHD streams makes kodi freeze

### ISSUE THREAD

**Issue by tstrul1** [bugatsinho/bugatsinho.github.io#76]
Hey,
recently when im try playing streams in sportHD my kodi freezes and needs to be force stopped.
Kodi 19.1
Windows 10

Debug log: https://pastebin.com/raw/APVKzAxm

**Comment by bugatsinho** [comment]
do you have inputstream enabled?  This log is just a part of the error

**Comment by tstrul1** [comment]
Hey,
Sorry for the delay, i have been doing some diagnose and looks like the problem is from my side.
this site site doesn't load streams via browser as well, even after turning ad blocker and changing dns.
if i word via cellular network/vpn it works...
