### ISSUE TITLE
Greek Subs bug?

### ISSUE THREAD

**Issue by baltzis** [bugatsinho/bugatsinho.github.io#77]
Greek subs is great! I don't, however, understand why the addon gets subtitles only from SUBZ, since it finds files from other providers as well. The addon produces an error each time I try to get a subtitle from S4F or [other].

Thanks for this addon, anyway!

**Comment by bugatsinho** [comment]
By say get you mean download right? as the addon gets subtitles from subz/s4f/yifi 
NOw s4f subs mostly are rar files and this is causing the issue. if you try different version probably you will get a zip sub and finally addon will download it

**Comment by baltzis** [comment]
Thanks for the prompt reply.
