### ISSUE TITLE
SportHD not working

### ISSUE THREAD

**Issue by Micah89x** [bugatsinho/bugatsinho.github.io#79]
Hello,
Since yesterday, this add-on does not work for me. Links to broadcast are not played.

**Comment by pitsi** [comment]
A log would be helpful you know...
Having said that, I would post a log, but sporthd works fine on both my kodi 19.1 and 18.9 installations.

**Comment by Micah89x** [comment]
I didn't do anything and it started working, topic to be closed.

**Comment by Arthur1967** [comment]
It's been working fine for me the whole time so I'm not sure what was wrong but I'm glad it's working for you￼
