### ISSUE TITLE
sport hd stopped working

### ISSUE THREAD

**Issue by oliaros** [bugatsinho/bugatsinho.github.io#95]
hello out there,
sport hd stopped working today. Anything i can do?
Thanx for your support, oliaros

**Comment by oliaros** [comment]
SportHD v0.1.11

**Comment by daplam84** [comment]
List live events displayed empty, tested on Librelelec 9.2.8 and 10.0.1, Version 0.1.11

**Comment by bugatsinho** [comment]
website changed the source code that is why add-on doesn't work! plz also join my telegram group for quick updates. I tried to fix it but now the view on the events are mess. check website sporthd.me
