### ISSUE TITLE
Blocked in uk help

### ISSUE THREAD

**Issue by Pawman63** [bugatsinho/bugatsinho.github.io#99]
Any chance of an update for uk users now bbrls.in has been created?

**Comment by bugatsinho** [comment]
it seems you don't use the add-on. check again the available domains on add-on settings. cheers

**Comment by bugatsinho** [comment]
![image](https://user-images.githubusercontent.com/18536253/156888365-d7163294-af7c-40ea-8f07-38703315742c.jpeg)

**Comment by Pawman63** [comment]
Fair enough had not tried addon since beginning of march and did not realise domain's could be added sans update, my ignorance on display.

**Comment by bugatsinho** [comment]
FYI addon gets the domains through a pastebin link so no reason for update.
